services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    container_name: teste_postgres

  nginx:
    image: nginx
    container_name: teste_nginx